`ifndef DEFINE_STATE

// This defines the states
typedef enum logic [1:0] {
	S_IDLE,
	S_ENABLE_UART_RX,
	S_WAIT_UART_RX,
	S_M1_enable
} top_state_type;

typedef enum logic [4:0] {
	S_M1_IDLE,
	LEAD_IN_0,
	LEAD_IN_1,
	LEAD_IN_2,
	LEAD_IN_3,
	LEAD_IN_4,
	LEAD_IN_5,
	COMM_CASE_1_0,
	COMM_CASE_1_1,
	COMM_CASE_1_2,
	COMM_CASE_1_3,
	COMM_CASE_1_4,
	COMM_CASE_1_5,
	COMM_CASE_2_0,
	COMM_CASE_2_1,
	COMM_CASE_2_2,
	COMM_CASE_2_3,
	COMM_CASE_2_4,
	COMM_CASE_2_5,
	LEAD_OUT_0,
	LEAD_OUT_1,
	LEAD_OUT_2,
	LEAD_OUT_3,
	LEAD_OUT_4,
	LEAD_OUT_5
	
} M1_state_type;


typedef enum logic [1:0] {
	S_RXC_IDLE,
	S_RXC_SYNC,
	S_RXC_ASSEMBLE_DATA,
	S_RXC_STOP_BIT
} RX_Controller_state_type;

typedef enum logic [2:0] {
	S_US_IDLE,
	S_US_STRIP_FILE_HEADER_1,
	S_US_STRIP_FILE_HEADER_2,
	S_US_START_FIRST_BYTE_RECEIVE,
	S_US_WRITE_FIRST_BYTE,
	S_US_START_SECOND_BYTE_RECEIVE,
	S_US_WRITE_SECOND_BYTE
} UART_SRAM_state_type;

typedef enum logic [3:0] {
	S_VS_WAIT_NEW_PIXEL_ROW,
	S_VS_NEW_PIXEL_ROW_DELAY_1,
	S_VS_NEW_PIXEL_ROW_DELAY_2,
	S_VS_NEW_PIXEL_ROW_DELAY_3,
	S_VS_NEW_PIXEL_ROW_DELAY_4,
	S_VS_NEW_PIXEL_ROW_DELAY_5,
	S_VS_FETCH_PIXEL_DATA_0,
	S_VS_FETCH_PIXEL_DATA_1,
	S_VS_FETCH_PIXEL_DATA_2,
	S_VS_FETCH_PIXEL_DATA_3
} VGA_SRAM_state_type;

`define DEFINE_STATE 1
`endif
